services:
  mongo_compare_service:
    image: mongo:6.0
    ports:
      - "5775:27017"
    volumes:
      - mongo_scrape_service_data:/data/db
    networks:
      - app_network

  compare_service:
    hostname: compare_service
    container_name: compare_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50054:50054"
    environment:
      - PORT=50054
      - MONGODB_URI=mongodb://mongo_compare_service:27017/
      - KAFKA_BROKER=broker:29092
    depends_on:
      - mongo_compare_service
    networks:
      - app_network
volumes:
  mongo_scrape_service_data:

networks:
  app_network:
    external: true
