# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: compare.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'compare.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcompare.proto\"\'\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\t\"(\n\nComparison\x12\x1a\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\t.KeyValue\"6\n\x14GetComparisonRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2H\n\x11\x43omparisonService\x12\x33\n\rGetComparison\x12\x15.GetComparisonRequest\x1a\x0b.Comparisonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compare_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYVALUE']._serialized_start=17
  _globals['_KEYVALUE']._serialized_end=56
  _globals['_COMPARISON']._serialized_start=58
  _globals['_COMPARISON']._serialized_end=98
  _globals['_GETCOMPARISONREQUEST']._serialized_start=100
  _globals['_GETCOMPARISONREQUEST']._serialized_end=154
  _globals['_RESPONSE']._serialized_start=156
  _globals['_RESPONSE']._serialized_end=183
  _globals['_COMPARISONSERVICE']._serialized_start=185
  _globals['_COMPARISONSERVICE']._serialized_end=257
# @@protoc_insertion_point(module_scope)
